[release-4.10] Bug 2105653: egressIP: node retrieval failure is not respected, causes panic
openshift/ovn-kubernetes pull request #1185
Opened 2022-07-11 18:51 UTC by tssurya

Fixes panic seen during checkEgressNodesReachability
E0606 11:57:34.063567       1 egressip.go:2096] Node:
huirwang-0606c-m5w24-worker-2-dkjmc reachability changed, but could not
retrieve node from cache, err: node
"huirwang-0606c-m5w24-worker-2-dkjmc" not found
W0606 11:57:34.063658       1 egressip.go:1657] Unable to remove GARP
configuration on external logical switch port for egress node:
huirwang-0606c-m5w24-worker-2-dkjmc, err: object not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x176626d]

goroutine 487 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).checkEgressNodesReachability(0xc000171c00)
	/home/surya/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/egressip.go:2099
+0x3ed
created by
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).initClusterEgressPolicies
	/home/surya/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/egressip.go:1772
+0xdb

The problem here is that the node retrieval fails since the node has
already been deleted, instead of respecting that failure we just
log the error saying node object not found and actually continue
to use that object further in the code which causes this panic.

Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
(cherry picked from commit 36176e5fcc4fb36ce175a02770f84c4556c6ef76)
(cherry picked from commit f436d25441dfbbf6dbd08c4d9535032426be923f)

Conflicts:
go-controller/pkg/ovn/egressip.go
go-controller/pkg/ovn/obj_retry.go

Since https://github.com/ovn-org/ovn-kubernetes/pull/2965 (EIP retry)
is missing in 4.10 and below

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

2022-07-11 20:10 UTC, flavio-fernandes reviewed
Looked at this change and what we did in pr https://github.com/ovn-org/ovn-kubernetes/pull/3019 . 
TY @tssurya !
/lgtm

2022-07-11 20:27 UTC, flavio-fernandes commented
/test e2e-gcp-ovn

2022-07-12 07:03 UTC, huiran0826 commented
/label qe-approved

2022-07-12 09:48 UTC, tssurya commented
/retest

2022-07-12 11:51 UTC, tssurya commented
we seem to be hitting https://bugzilla.redhat.com/show_bug.cgi?id=2106163 in the CI

2022-07-12 12:22 UTC, tssurya commented
/retest-required

2022-07-12 13:50 UTC, tssurya commented
/retest

2022-07-12 20:00 UTC, trozet requested changes

2022-07-12 20:00 UTC, trozet commented on go-controller/pkg/ovn/egressip.go
>  				klog.Errorf("Node: %s reachability changed, but could not retrieve node from cache, err: %v", node.Name, err)
this will still cause a panic cause err !=nil and accessing nil node object Name field. We can just remove this entire GetNode since it doesnt look like its being used.

2022-07-12 20:27 UTC, tssurya commented on go-controller/pkg/ovn/egressip.go
>  				klog.Errorf("Node: %s reachability changed, but could not retrieve node from cache, err: %v", node.Name, err)
100% yes
thanks for the catch, I ported the two commits we talked about here.

2022-07-12 20:48 UTC, tssurya commented on go-controller/pkg/ovn/egressip.go
>  				klog.Errorf("Node: %s reachability changed, but could not retrieve node from cache, err: %v", node.Name, err)
was a bad rebase actually, seems like my original fix removed this completely and I lost it under conflicts...
https://github.com/ovn-org/ovn-kubernetes/pull/3019/files#r891363448

2022-07-13 13:24 UTC, flavio-fernandes commented
/lgtm

2022-07-19 16:44 UTC, trozet commented
/approve

2022-07-20 01:35 UTC, huiran0826 commented
/label cherry-pick-approved

2022-07-20 07:03 UTC, merged