[release-4.10] Bug 2109442: Fix GetPodsBySelector/GetNamespacesBySelector so MatchExpressions is respected
openshift/ovn-kubernetes pull request #1195
Opened 2022-07-14 13:52 UTC by Reamer

Previously only MatchLabels was used to create a label selector and MatchExpressions was ignored

Signed-off-by: Patryk Diak <pdiak@redhat.com>

2022-07-21 08:28 UTC, Reamer commented
/bugzilla refresh

2022-07-21 08:43 UTC, vrutkovs commented
/bugzilla refresh

2022-07-21 08:45 UTC, vrutkovs commented
/bugzilla refresh
/ok-to-test

2022-07-21 20:29 UTC, anuragthehatter commented
/label qe-approved

2022-07-22 09:57 UTC, andreaskaris commented
Hi,

Thanks for opening this PR. Please change the title to be:
~~~
[release-4.10] Bug 2109442: Fix GetPodsBySelector/GetNamespacesBySelector so MatchExpressions is respected
~~~

Please amend your cherry-pick to refer to the original (4.11) commit:
~~~
git cherry-pick -x <original commit number>
~~~

2022-07-22 14:05 UTC, flavio-fernandes requested changes
Please add this to the commit message:

```
(cherry picked from commit 96b2a2555a654d72a8546366032063a98a016f29)
```
Otherwise, LGTM!

Also, I'm assuming that we need this to be back ported to 4.8, right? If so, I
will use the bot to merge to 4.9 fro this PR once it merges.

Thanks,
-- flaviof

2022-07-22 14:19 UTC, Reamer commented
@andreaskaris done
@flavio-fernandes done


> Also, I'm assuming that we need this to be back ported to 4.8, right? If so, I will use the bot to merge to 4.9 from this PR once it merges.

I have recently updated to okd 4.10. In this version I noticed the error when using egressIPs. Under okd 4.9 and 4.8 I did not have this problem when using EgressIPs. Whether the cherry pick is also needed there I do not know. But since it is a correction in a quite central place, it should be checked.

2022-07-22 14:22 UTC, flavio-fernandes approved these changes
/lgtm

2022-07-22 17:17 UTC, vrutkovs commented
>Also, I'm assuming that we need this to be back ported to 4.8, right? If so, I will use the bot to merge to 4.9 from this PR once it merges.

That might be useful for OCP. In OKD we only have one stream, which is 4.10 atm, so not really required for us

2022-07-22 17:17 UTC, vrutkovs commented
/retitle [release-4.10] Bug 2109442: Fix GetPodsBySelector/GetNamespacesBySelector so MatchExpressions is respected

2022-07-22 18:09 UTC, flavio-fernandes commented
/retest-required

2022-07-23 10:42 UTC, flavio-fernandes commented
/retest-required

2022-07-24 07:07 UTC, Reamer commented
/retest-required

2022-07-24 16:57 UTC, Reamer commented
/retest-required

2022-07-24 17:37 UTC, Reamer commented
/retest

2022-07-25 04:07 UTC, Reamer commented
/retest

2022-07-25 06:06 UTC, Reamer commented
/retest

2022-07-25 08:58 UTC, Reamer commented
/retest

2022-07-25 13:15 UTC, Reamer commented
/assign @dcbw

2022-07-25 13:52 UTC, trozet approved these changes
/lgtm

2022-07-25 13:53 UTC, trozet commented
/label backport-risk-assessed

2022-07-25 14:16 UTC, trozet commented
/assign @anuragthehatter

2022-08-04 15:23 UTC, anuragthehatter commented
/label cherry-pick-approved

2022-08-05 02:05 UTC, merged

2022-08-05 18:04 UTC, flavio-fernandes commented
/cherry-pick release-4.9