Bug 2117078: [release-4.7] Multiple ExGW cache validation/improvements
openshift/ovn-kubernetes pull request #1241
Opened 2022-08-09 22:57 UTC by trozet

Minor conflicts in the 2nd and 3rd commit

2022-08-09 22:58 UTC, trozet commented
/assign @dcbw

2022-08-18 18:11 UTC, trozet commented
/label backport-risk-assessed

2022-08-18 19:40 UTC, tssurya requested changes
COMMIT1: CLEAN PICK LGTM
COMMIT2: PTAL my comment AND should we be bringing in https://github.com/openshift/ovn-kubernetes/commit/988fbb134e6e65f0f354b512b82b7ce496b3aa6f#diff-3696280f7dbfece2e1136d5fa06a3339a05a8a3067710f7510ecdefba51bcb29R194 ? I moved the `parseRoutingExternalGWAnnotation` into utils I see.. but do we need to bring it down?

2022-08-18 19:40 UTC, tssurya commented on go-controller/pkg/ovn/egressgw.go
> +	var gws string
hmmm why are you bringing in L169 to L175 ? we no longer need it since we aren't using `gws` anywhere...

2022-08-18 19:40 UTC, tssurya commented on go-controller/pkg/ovn/namespace.go
> +			if foundPod, ok := ipTracker[gwIP]; ok {
self note: line different from 4.8 pick since we don't need this to be gwIP.String() since we converted these variables into strings as part of that conntrack backport.

2022-08-18 19:43 UTC, tssurya reviewed
COMMIT 3 & 4 LGTM

2022-08-18 19:43 UTC, tssurya commented on go-controller/pkg/ovn/egressgw.go
> +	delete(nsInfo.routingExternalPodGWs, podGWKey)
assuming conflict was here somewhere? But code change lgtm based on comparision with https://github.com/openshift/ovn-kubernetes/commit/18c8afe2d4cf6adfc6d7a3396b980d2050246a7b.

2022-08-18 21:29 UTC, trozet commented on go-controller/pkg/ovn/egressgw.go
> +	var gws string
oops removing...

2022-08-19 19:36 UTC, tssurya commented
/lgtm

2022-08-19 19:37 UTC, tssurya commented
/retest

2022-08-22 18:22 UTC, anuragthehatter commented
/label cherry-pick-approved

2022-08-26 20:40 UTC, trozet commented
/retest-required

2022-08-26 22:20 UTC, merged