Bug OCPBUGS-574: EgressGW: don't error out trying to add SPK when a pod without ip exists
openshift/ovn-kubernetes pull request #1252
Opened 2022-08-25 08:43 UTC by oribon

When the SPK is added and is serving an ICNI namespace, we will search all of the pods in the served namespace to update their routes to point to this new SPK.
If for some reason one of the pods in the namespace has no IPs, we error out trying to add the SPK.
The correct behavior should just be to warn that the pod IPs are missing and continue with adding the SPK.

Signed-off-by: Ori Braunshtein <obraunsh@redhat.com>

This is fixed in 4.10+ by https://github.com/openshift/ovn-kubernetes/commit/b94351d79ce9770a726678d26be5d67b549be83f

2022-08-25 12:55 UTC, oribon commented
/retest

2022-08-28 06:56 UTC, oribon commented
/retest

2022-08-28 11:22 UTC, oribon commented
/retest

2022-08-30 21:08 UTC, trozet requested changes

2022-08-30 21:08 UTC, trozet commented on go-controller/pkg/ovn/egressgw.go
> +			klog.Warningf("Will not add gateway routes pod %s/%s. IPs not found!", pod.Namespace, pod.Name)
nit: "Will not add gateway routes for pod %s/%s

2022-08-31 05:55 UTC, oribon commented on go-controller/pkg/ovn/egressgw.go
> +			klog.Warningf("Will not add gateway routes pod %s/%s. IPs not found!", pod.Namespace, pod.Name)
done

2022-08-31 09:22 UTC, oribon commented
/retest

2022-08-31 16:01 UTC, trozet commented
/lgtm
/label backport-risk-assessed

2022-09-23 14:45 UTC, anuragthehatter commented
/label cherry-pick-approved

2022-09-28 06:21 UTC, oribon commented
/retest-required

2022-09-28 09:07 UTC, merged

2022-09-28 09:09 UTC, oribon commented
/cherry-pick release-4.8