[release-4.12] OCPBUGS-298: Bump OVN to 22.09.0-54
openshift/ovn-kubernetes pull request #1488
Opened 2023-01-24 09:55 UTC by kyrtapz

Bumped OVN to latest available for 22.09.

2023-01-24 09:58 UTC, kyrtapz commented
/jira refresh

2023-01-24 13:10 UTC, tssurya requested changes
> Bumped OVN to latest available for 22.09.

@kyrtapz : can you please outline the changes you are bringing in? difficult to judge the risks/pros/cons/what other bugfixes you are bringing in

2023-01-24 13:11 UTC, tssurya commented
its a minor bump so shouldn't be many changes..

2023-01-24 13:18 UTC, tssurya commented
> > Bumped OVN to latest available for 22.09.
> 
> @kyrtapz : can you please outline the changes you are bringing in? difficult to judge the risks/pros/cons/what other bugfixes you are bringing in

was there in the commit message, kinda missed it

2023-01-24 15:12 UTC, tssurya commented
/lgtm

2023-01-25 01:16 UTC, rbbratta commented
/label cherry-pick-approved

2023-01-25 09:26 UTC, npinaeva commented
/retitle [release-4.12] OCPBUGS-298, OCPBUGS-6637: Bump OVN to 22.09.0-54

2023-01-25 09:28 UTC, npinaeva commented
/retitle [release-4.12] OCPBUGS-298: Bump OVN to 22.09.0-54

2023-01-25 10:38 UTC, kyrtapz commented
/retest

2023-01-25 17:58 UTC, trozet commented
/label backport-risk-assessed

2023-01-25 17:59 UTC, trozet commented
/override ci/prow/e2e-metal-ipi-ovn-dualstack

2023-01-25 20:29 UTC, merged