[release-4.11] OCPBUGS-5245: Move check_pkt_larger to gateway router ports
openshift/ovn-kubernetes pull request #1505
Opened 2023-02-02 04:04 UTC by flavio-fernandes

A series of patches around 947e8d450ebaa8ce4ab81cb480a419618f1508c7
in the ovn-org/ovn repository now enable check_pkt_larger for gateway
router ports. Take advantage of this new feature to solve https://issues.redhat.com/browse/OCPBUGS-2827
Also see: http://patchwork.ozlabs.org/project/ovn/cover/cover.1627405420.git.lorenzo.bianconi@redhat.com/

For release 4.11, this means that OVN 22.06.0-101 or newer would be required. Bumping release 4.11 to pick up
that change is being done in a separate PR.

Conflicts:

- go-controller/pkg/node/gateway.go
  - Logic for SetGatewayMTUSupport needed to account for missing DPU changes that are not part of 4.11. In other words, work w/out  https://github.com/openshift/ovn-kubernetes/pull/1368
- go-controller/pkg/node/gateway_init_linux_test.go
  - shareGatewayInterfaceTest does have netlink.Link in 4.11
- go-controller/pkg/ovn/gateway_test.go
  - gatewayInit
- go-controller/pkg/ovn/hybrid_test.go
  - Does not exist in 4.11
- go-controller/pkg/ovn/master_test.go
  - generateGatewayInitExpectedNB
- go-controller/pkg/ovn/namespace_test.go
  - Adding new MTU param
- go-controller/pkg/ovn/obj_retry_master.go
  - In 4.11, this file is called go-controller/pkg/ovn/obj_retry.go
- go-controller/pkg/ovn/ovn.go

Notes for reviewers:

a) I spawned this specific PR with kind upstream:

```
contrib/kind.sh
```

b) I then ran the E2E tests successfully:

```
cd test/e2e
go test . -v -ginkgo.v -ginkgo.focus ".*when a nodePort service targeting a pod with hostNetwork:.*"
(...)
Ran 4 of 118 Specs in 65.941 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 114 Skipped
```

c) And I also made sure that annotation updates updated the Logical_Router_Ports:

```
$ oc rsh -n ovn-kubernetes       ovnkube-db-5c6757846-7swtb
#  ovn-nbctl list Logical_Router_Port | grep mtu
options             : {gateway_mtu="1400"}
options             : {gateway_mtu="1400"}
options             : {gateway_mtu="1400"}
```

```
[root@ovnkubernetes e2e]# oc annotate node  ovn-worker k8s.ovn.org/gateway-mtu-support=false
node/ovn-worker annotated
```

```
# ovn-nbctl list Logical_Router_Port | grep mtu
options             : {gateway_mtu="1400"}
options             : {gateway_mtu="1400"}
```

2023-02-02 04:05 UTC, flavio-fernandes commented
/assign @andreaskaris

2023-02-02 04:19 UTC, flavio-fernandes commented on go-controller/pkg/node/gateway.go
> +			klog.Warningf("OVS does not support check_packet_length action. " +
@andreaskaris this was very tricky for me to backport. Your eagle eyes here would be much appreciated.

2023-02-02 18:38 UTC, flavio-fernandes commented
/retest-required

2023-02-03 09:41 UTC, andreaskaris commented
/retest-required

2023-02-03 10:59 UTC, andreaskaris requested changes
I skimmed a little bit through the respective tests, but I ran the e2e locally and also `make test` plus the disable check (see my comment above).
Other than that one line that IMO can and should be removed (to be verified), this looks ok to me

2023-02-03 10:59 UTC, andreaskaris commented on go-controller/pkg/ovn/obj_retry.go
> +// // addDeleteToRetryObj adds an old object that needs to be cleaned up to a retry object
Shall we just remove this instead of commenting it?

2023-02-03 10:59 UTC, andreaskaris commented on go-controller/pkg/node/gateway.go
>  			config.Gateway.DisablePacketMTUCheck = true
Is this line `config.Gateway.DisablePacketMTUCheck = true`  still needed? Upstream, I removed it

2023-02-03 19:21 UTC, flavio-fernandes commented on go-controller/pkg/ovn/obj_retry.go
> +// // addDeleteToRetryObj adds an old object that needs to be cleaned up to a retry object
Yeah, I think we can.

2023-02-03 20:20 UTC, flavio-fernandes commented
> [Fail]

yeah, I think I broke something. Checking....

2023-02-03 22:57 UTC, flavio-fernandes commented on go-controller/pkg/node/gateway.go
>  			config.Gateway.DisablePacketMTUCheck = true
You are right... not needed. Will remove it.

2023-02-04 00:27 UTC, flavio-fernandes commented
/test e2e-vsphere-ovn

2023-02-04 14:26 UTC, flavio-fernandes commented
/retest-required

2023-02-04 14:26 UTC, flavio-fernandes commented
/test e2e-vsphere-ovn

2023-02-04 14:27 UTC, flavio-fernandes commented
/assign @trozet

2023-02-04 15:45 UTC, flavio-fernandes commented
/test e2e-metal-ipi-ovn-dualstack
```
{  e 1: cd: /root/dev-scripts: No such file or directory
bash: line 2: common.sh: No such file or directory
bash: line 3: ocp_install_env.sh: No such file or directory
bash: line 4: utils.sh: No such file or directory
bash: line 5: network.sh: No such file or directory
bash: line 11: openshift_version: command not found
scp: /tmp/must-gather-image.sh: No such file or directory
### Gathering logs...
bash: line 1: cd: dev-scripts: No such file or directory
Get install-gather, if there is one...
cp: cannot stat '/root/dev-scripts/ocp/*/log-bundle*.tar.gz': No such file or directory
Get sosreport including sar data...
temporary directory /tmp/artifacts does not exist or is not writable
Get libvirt logs...
tar: /var/log/libvirt/qemu: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar (child): /tmp/artifacts/libvirt-logs-r640-02.cluster1.metal-platform.eng.rdu2.redhat.com.tar.gz: Cannot open: No such file or directory
```

2023-02-06 05:33 UTC, flaper87 commented
/test e2e-metal-ipi-ovn-dualstack

2023-02-06 15:01 UTC, flavio-fernandes commented
@trozet @jcaamano @dcbw can I ask you for an override ?
/override ci/prow/e2e-metal-ipi-ovn-dualstack
Failure is fixed by https://github.com/openshift/ovn-kubernetes/pull/1500 but that's not yet backported to 4.11

2023-02-06 15:03 UTC, dcbw commented
/override ci/prow/e2e-metal-ipi-ovn-dualstack

2023-02-06 22:26 UTC, flavio-fernandes commented
**Update:** Verified fix on `real` cluster (outside kind).

```
❯ oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.11.0-0.nightly-2023-02-02-105102   True        False         21m     Cluster version is 4.11.0-0.nightly-2023-02-02-105102

❯ oc get infrastructures.config.openshift.io cluster  -o jsonpath='{.status.platform}'
GCP

❯ go test . -v -ginkgo.v -ginkgo.focus ".*when a nodePort service targeting a pod with hostNetwork:.*"
...
Ran 4 of 131 Specs in 45.334 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 127 Skipped

--- PASS: TestE2e (45.37s)
PASS
ok      github.com/ovn-org/ovn-kubernetes/test/e2e      45.424s
```

2023-02-07 10:06 UTC, andreaskaris commented
/lgtm

2023-02-08 15:47 UTC, trozet commented
/approve

2023-02-08 15:53 UTC, trozet commented
/label backport-risk-assessed

2023-02-08 16:11 UTC, anuragthehatter commented
/label cherry-pick-approved

2023-02-08 19:06 UTC, flavio-fernandes commented
/retest-required

2023-02-09 16:53 UTC, flavio-fernandes commented
/retest-required

2023-02-09 20:29 UTC, flavio-fernandes commented
/test e2e-gcp-ovn

2023-02-09 22:48 UTC, merged