Ocpbugs 5889 release412
openshift/ovn-kubernetes pull request #1581
Opened 2023-03-15 10:03 UTC by zeeke

**- What this PR does and why is it needed**

Backport of:
- https://github.com/openshift/ovn-kubernetes/pull/1567

**- Special notes for reviewers**

Optimization about skipping pods on different nodes while search colliding IP has been removed, as nodeName is not present in `handlePeerPodSelectorDelete`

See [pkg/ovn/pods.go#L256](https://github.com/openshift/ovn-kubernetes/blob/f65d02b84f7acf787f53f11710916d871e8f2d5b/go-controller/pkg/ovn/pods.go#L256)

```
				if util.PodCompleted(p) || !util.PodWantsNetwork(p) || !util.PodScheduled(p) || p.Spec.NodeName != nodeName {
					continue
				}
```

**- How to verify it**

**- Description for the changelog**

2023-03-15 10:04 UTC, zeeke commented
/jira cherrypick OCPBUGS-8741

2023-03-15 15:10 UTC, zeeke commented
/retest

2023-03-16 10:48 UTC, zeeke commented
/retest

failing test:
```
 [sig-arch][Late] operators should not create watch channels very often [apigroup:config.openshift.io] [Suite:openshift/conformance/parallel] 
```

2023-03-16 13:28 UTC, zeeke commented
/retest

2023-03-17 09:08 UTC, zeeke commented
/retest

2023-03-21 20:07 UTC, dcbw commented
/jira refresh

2023-03-22 07:59 UTC, zeeke commented
/cherrypick release-4.11

2023-03-24 09:15 UTC, tssurya requested changes
I am almost lgtm, just one question: please see my comment on adding back the nodeName match?

2023-03-24 09:15 UTC, tssurya commented on go-controller/pkg/ovn/pods.go
> +		if util.PodCompleted(p) || !util.PodWantsNetwork(p) || !util.PodScheduled(p) {
Should we be adding back the `|| p.Spec.NodeName != nodeName` here? 
Example in https://github.com/openshift/ovn-kubernetes/pull/1567/files?diff=unified&w=0#diff-941b484ab7f41b84a6ba9c2dee91f3454401447db0ca70cb401a8cc582cc072eR299 we moved `|| expectedSwitchName != switchName` check to before`findPodWithIPAddresses`. Wondering why we are dropping this check here.

2023-03-24 09:19 UTC, tssurya commented on go-controller/pkg/ovn/pods.go
> +		if util.PodCompleted(p) || !util.PodWantsNetwork(p) || !util.PodScheduled(p) {
note that I have read your PR description where you say you didn't do this because `handlePeerPodSelectorDelete` doesn't have nodeName... but we could just pass empty string from there but do it at least in the main logic? It just seems like we are kinda dropping that thing out of the blue compared to what we used to do.

2023-03-24 09:33 UTC, zeeke commented on go-controller/pkg/ovn/pods.go
> +			var needleIPs []net.IP
Yes: "haystack and needle" are sometimes used as [search function parameters](https://www.php.net/manual/en/function.array-search.php). I didn't find any better names :smiley:

2023-03-24 10:05 UTC, zeeke commented on go-controller/pkg/ovn/pods.go
> +		if util.PodCompleted(p) || !util.PodWantsNetwork(p) || !util.PodScheduled(p) {
Good point! The fact is that that check has already been dropped in 4.13+ by [1], as neither `expectedSwitchName` 
 nor `switchName` are calculated from `p.Spec.NodeName`.

The changes you are proposing make release-4.12 branch diverge a little from master.

Saying that, if you are still in favor of restoring the check, I can go for it.

[1] https://github.com/ovn-org/ovn-kubernetes/commit/f620c6c6adbb2a2367eabb5c86b6fd2b0e831272#diff-941b484ab7f41b84a6ba9c2dee91f3454401447db0ca70cb401a8cc582cc072eR195

2023-03-24 15:52 UTC, tssurya commented
/lgtm

2023-03-24 15:53 UTC, tssurya commented
@trozet for backport-risk-assess

2023-03-24 15:53 UTC, zeeke commented on go-controller/pkg/ovn/pods.go
> +		if util.PodCompleted(p) || !util.PodWantsNetwork(p) || !util.PodScheduled(p) {
Thanks @tssurya!

2023-03-27 11:10 UTC, zeeke commented
@zhaozhanqi @anuragthehatter
can you have a look at this and add cherry-pick-approved ?

2023-03-28 02:07 UTC, zhaozhanqi commented
/label cherry-pick-approved

2023-03-28 15:20 UTC, zeeke commented
/retest-required

2023-03-28 21:03 UTC, dcbw commented
/override ci/prow/e2e-vsphere-windows 

Known flake https://redhat-internal.slack.com/archives/CM4ERHBJS/p1680032625731999

2023-03-28 21:05 UTC, dcbw commented
/tide refresh

2023-03-28 21:06 UTC, merged