OCPBUGS-10592: Install pyOpenSSL and pip packages for ovn-detrace
openshift/ovn-kubernetes pull request #1605
Opened 2023-03-24 08:58 UTC by pperiyasamy

It is a prerequisite to have ovs, pyOpenSSL python packages in ovnk pods to run ovn-detrace command (refer [here](https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/cmd/ovnkube-trace/ovnkube-trace.go#L887-L911)), so adding pyOpenSSL back into install pkgs. There is also possiblity to use pip3 command to install ovs and pyOpenSSL packages on a running pod. hence adding python3-pip as well into install pkgs.

2023-03-24 09:00 UTC, pperiyasamy commented
/assign @tssurya @dcbw

2023-03-31 11:29 UTC, pperiyasamy commented
> `Error: Unable to find a match: python3-pyOpenSSL`
> 
> This package doesn't exist in RHEL9... ovn-detrace doesn't actually use any SSL directly, it uses the OVS python bits that got ported to the Python internal SSL last year.

Yes @dcbw , ovn-detrace is working fine now without a need for dependency on `python3-pyOpenSSL`.
```
# ./ovnkube-trace --src-namespace openshift-dns -src dns-default-fvftq -dst-namespace openshift-dns -dst dns-default-p2msg -udp -dst-port 53 -loglevel 0
I0331 13:23:12.238444  566820 ovs.go:90] Maximum command line arguments set to: 191102
ovn-trace source pod to destination pod indicates success from dns-default-fvftq to dns-default-p2msg
ovn-trace destination pod to source pod indicates success from dns-default-p2msg to dns-default-fvftq
ovs-appctl ofproto/trace source pod to destination pod indicates success from dns-default-fvftq to dns-default-p2msg
ovs-appctl ofproto/trace destination pod to source pod indicates success from dns-default-p2msg to dns-default-fvftq
ovn-detrace source pod to destination pod indicates success from dns-default-fvftq to dns-default-p2msg
ovn-detrace destination pod to source pod indicates success from dns-default-p2msg to dns-default-fvftq
```
Updated the PR with changing ovn-detrace dependency check accordingly.

2023-03-31 11:32 UTC, pperiyasamy commented
/retest-required

2023-04-04 14:40 UTC, tssurya requested changes

2023-04-04 14:40 UTC, tssurya commented on Dockerfile
> +	openssl python3-pip firewalld-filesystem \
I was just telling about the `pythonOpenSSL` stuff here: https://github.com/openshift/ovn-kubernetes/pull/1553#discussion_r1129434693
I am going to leave the same comment I left here: https://github.com/openshift/ovn-kubernetes/pull/1553#discussion_r1133798426

I think we need to start adding some comments on why packages are being added else its difficult to keep track

I would make this:
RUN INSTALL_PKGS=" \
	openssl firewalld-filesystem \
	python3-pip  \ # add comment here why you are adding this so that in future people know not to remove this.

and its not totally your fault since nobody did this in the past, but we need to start somewhere...

2023-04-06 15:04 UTC, tssurya approved these changes
/lgtm

2023-04-06 15:04 UTC, tssurya commented on Dockerfile
> +	openssl python3-pip firewalld-filesystem \
yes lgtm thanks.

2023-04-06 15:16 UTC, pperiyasamy commented
/retest-required

2023-04-10 10:52 UTC, jcaamano commented
@pperiyasamy `Dockerfile.base` already installs `python3-openvswitch3.1` and pip is used to install the same library. Do we need the pip version for a specific reason? Otherwise, it is a possibility to remove the need to install ovs with pip and remove the need for pip altogether. Not a strong opinion. maybe it is useful to keep pip around, but I am surprised that we use it to install a library that should be already in place.

2023-04-12 08:56 UTC, pperiyasamy commented
> @pperiyasamy `Dockerfile.base` already installs `python3-openvswitch3.1` and pip is used to install the same library. Do we need the pip version for a specific reason? Otherwise, it is a possibility to remove the need to install ovs with pip and remove the need for pip altogether. Not a strong opinion. maybe it is useful to keep pip around, but I am surprised that we use it to install a library that should be already in place.

@jcaamano the pip package is needed by ovn-detrace command ([here](https://github.com/openshift/ovn-kubernetes/blob/master/go-controller/cmd/ovnkube-trace/ovnkube-trace.go#L901)) as its used for installing its dependency ovs package. hence adding python3-pip into `Dockerfile.base` . But I'm not sure at what scenario this happens because ovs package is already there in the ovnk pods.

2023-04-25 12:14 UTC, pperiyasamy commented
/retest-required

2023-04-25 12:33 UTC, jcaamano commented
So I think that we don't need to add python-pip if we know we satisfy ovnkube-trace dependencies in our base image.

For people using ovnkube-trace in other ways, the pyOpenSSL check could be changed to 
```
"pyOpenSSL": "if python -c 'import ssl; print(ssl.OPENSSL_VERSION)'; then echo 'true'; fi"
```

But I guess that needs to be an upstream change first?

2023-04-26 11:51 UTC, tssurya commented
@pperiyasamy explained the fix that we are doing upstream: https://github.com/ovn-org/ovn-kubernetes/pull/3549 and so we don't need this anymore.. SGTM.

2023-04-26 11:53 UTC, tssurya commented
/close

2023-04-26 11:53 UTC, closed without merging