matched comment to new function name
openshift/ovn-kubernetes pull request #1698
Opened 2023-06-06 22:02 UTC by juanino

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

2023-06-07 00:09 UTC, Conan-Kudo approved these changes

2023-06-07 08:24 UTC, tssurya requested changes
Thanks for your contribution, Please close this PR and open one upstream first. We will then bring that in automatically.

2023-06-07 08:24 UTC, tssurya commented on go-controller/pkg/cni/utils.go
> +// GetPodWithAnnotations obtains the pod UID and annotation from the cache or apiserver
please submit a PR upstream first: https://github.com/ovn-org/ovn-kubernetes and then it will be brought down from there automatically.

2023-06-08 00:25 UTC, closed without merging

2023-06-08 00:26 UTC, juanino commented
ok, if you have directions let me know, otherwise i will RTFM-- newb.