[OCPBUGS-18935] Bump version of dependency safchain/ethtool
openshift/ovn-kubernetes pull request #1974
Opened 2023-12-06 11:51 UTC by werled

**- What this PR does and why is it needed**
This PR updates the version to include the fix to safchain/ethtools for https://issues.redhat.com/browse/OCPBUGS-18935 (enable changing of interface features on s390x).

This PR allows follow-up work on https://issues.redhat.com/browse/OCPBUGS-18394, removing a workaround needed for x86 clusters with s390x nodes attached and additionally reenabling the use of ethtools on s390x clusters in general (https://github.com/openshift/cluster-network-operator/pull/1629, https://github.com/openshift/cluster-network-operator/pull/1655)

**- Special notes for reviewers**
safchain/ethtools only depends on golang.org/x/sys but this change also increases the depended on version (from v0.6.0 to v0.13.0).

The change in [go-controller/vendor/k8s.io/client-go/informers/factory.go] already happens just running `go mod tidy` and `go mod vendor` without increasing the safchain/ethtool version.

Steps done for this commit:
* replace: `github.com/safchain/ethtool v0.3.0` with `github.com/safchain/ethtool v0.3.1-0.20231027162144-83e5e0097c91` in [go.mod](https://github.com/openshift/ovn-kubernetes/compare/master...werled:openshift-ovn-kubernetes:ocpbugs-18935-bump-ethtool?expand=1#diff-ba0dc9eaa63468cc5319950de2ef7777e4b619199abae42c031c28d6541ec31fL36-R36), [vendor/modules.txt](https://github.com/openshift/ovn-kubernetes/compare/master...werled:openshift-ovn-kubernetes:ocpbugs-18935-bump-ethtool?expand=1#diff-175cf34b89792ff8fe1db8a4e992f6000a7cd3f2f37e61ffece0c7a14b89e90aL350-R350)
* `go mod tidy`
* `go mod vendor`

**- How to verify it**

**- Description for the changelog**

2023-12-06 16:23 UTC, werled commented
Since I suspect they were breaking a lot of the checks, I reverted the changes that were done by the go tool that are not related to safchain/ethtool bump. I kept them in a separate commit for now (f7b3df8) for easier overview.

2023-12-07 08:51 UTC, werled commented
> @werled I would just squash the two patches. We don't want to remove the unrelated changes.

@dcbw Done 👍. Just wanted to make sure that it's clear for the review what I did there.

2023-12-08 08:07 UTC, werled commented
/retest

2023-12-14 08:42 UTC, werled commented
/retest

2023-12-14 19:00 UTC, jaypoulz commented
/retest-required

2023-12-18 12:08 UTC, werled commented
/retest-required

2024-01-24 20:57 UTC, danwinship commented
@werled This should not be done in our local fork; the original code is in upstream ovn-kubernetes (https://github.com/ovn-org/ovn-kubernetes) so the fix should go there too so we don't have to keep it as a local patch.

2024-03-06 17:26 UTC, tssurya requested changes
/close

all changes have to merge into upstream first: https://github.com/ovn-org/ovn-kubernetes and we do weekly d/s sync merges

2024-03-06 17:26 UTC, closed without merging