[WIP] [release-4.13] initial testing of webhook admission plugin
openshift/ovn-kubernetes pull request #2053
Opened 2024-02-05 19:03 UTC by JacobTanenbaum

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

2024-02-06 14:13 UTC, JacobTanenbaum commented
/retest

2024-02-08 18:22 UTC, JacobTanenbaum commented
it appears that some tests tried to run before the image was checked it

/retest

2024-02-08 20:35 UTC, JacobTanenbaum commented
/retest

2024-02-09 16:25 UTC, JacobTanenbaum commented
/retest

2024-02-09 18:35 UTC, JacobTanenbaum commented
CI couldn't find the images for some reason
/retest

2024-02-14 18:51 UTC, jluhrsen commented
/retest

2024-02-20 15:29 UTC, JacobTanenbaum commented
/retest

2024-03-13 18:28 UTC, JacobTanenbaum commented
/retest

2024-03-14 13:39 UTC, JacobTanenbaum commented
looks like the e2e-metal-ipi-ovn-dualstack failed because something went wrong in the cluster 

/retest-required

2024-03-19 12:35 UTC, JacobTanenbaum commented
/retest-required

2024-03-26 08:18 UTC, kyrtapz commented on go-controller/cmd/ovnkube/ovnkube.go
> +		if err := util.StartNodeCertificateManager(ctx.Context, ovnKubeStartWg, &config.Kubernetes); err != nil {
In 4.14 and up we start the cert manager in hybrid overlay nodes as well, is it not required in 4.13?

2024-03-26 08:18 UTC, kyrtapz commented on go-controller/pkg/util/kube.go
> +	"context"
Please also pull in the fairly recent https://github.com/openshift/ovn-kubernetes/commit/788c977f1404d19fd2c0c3b54059ee3955ab2f40

2024-03-26 08:49 UTC, kyrtapz requested changes

2024-03-26 08:49 UTC, kyrtapz commented on go-controller/pkg/ovnwebhook/podadmission.go
> +var interconnectPodAnnotations = map[string]checkPodAnnot{
Please remove interconnect specific code from the backport.

2024-03-26 08:49 UTC, kyrtapz commented on go-controller/cmd/ovnkube-identity/ovnkubeidentity.go
> +	if len(cliCfg.csrAcceptanceConditions) > 1 {
This should be checking for `podAdmissionConditions`, I know it is the same in 4.14 but it is a bug that works because enable-interconect is always set.

2024-03-26 19:03 UTC, JacobTanenbaum commented on go-controller/cmd/ovnkube/ovnkube.go
> +		if err := util.StartNodeCertificateManager(ctx.Context, ovnKubeStartWg, &config.Kubernetes); err != nil {
what do you mean? `StartNodeCertificateManager()` is surrounded by the same check up to master

2024-03-26 19:32 UTC, JacobTanenbaum commented on go-controller/pkg/util/kube.go
> +	"context"
done

2024-03-26 19:32 UTC, JacobTanenbaum commented on go-controller/pkg/ovnwebhook/podadmission.go
> +var interconnectPodAnnotations = map[string]checkPodAnnot{
done

2024-03-26 19:50 UTC, JacobTanenbaum commented
/test unit

2024-03-27 13:39 UTC, JacobTanenbaum commented
/retest-required

2024-04-11 14:17 UTC, JacobTanenbaum commented
/retest-required

2024-04-22 17:19 UTC, JacobTanenbaum commented
/retest-required

looks like the dualstack test had issues during setup

2024-05-07 07:46 UTC, kyrtapz reviewed
/lgtm

Thanks Jacob!
One remaining question is the hybrid overlay, I don't see the changes backported here and we do have them in 4.14:
https://github.com/openshift/ovn-kubernetes/blob/49826e7229481b5b2bf19c87906493a538768c35/go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go#L106

2024-05-07 07:46 UTC, kyrtapz commented on go-controller/pkg/ovnwebhook/podadmission_test.go
> +		/*
Remove commented code .

2024-05-07 07:46 UTC, kyrtapz commented on go-controller/pkg/ovnwebhook/podadmission_test.go
> +		{
This is not a valid test any more?
We are not checking any changes made by ovnkube-node on pods since it is not doing any.
I think we should remove all of the `ovnkube-node can modify` tests.

2024-05-07 07:46 UTC, kyrtapz commented on go-controller/pkg/ovnwebhook/podadmission.go
> +	annotations       map[string]checkPodAnnot
`nodeLister`, `annotations` and `annotationKeys` are not set/used anywhere.
It should be safe to remove.

2024-05-07 07:46 UTC, kyrtapz commented on go-controller/pkg/ovnwebhook/podadmission.go
> +	if podAdmission == nil {
NIT: this can be moved before line 97 so we can assume that after this check the `podAdmission` is not nil.

2024-05-07 07:49 UTC, kyrtapz commented
The `e2e-aws-ovn-hypershift` job is perma failing, I am not sure if we even support hypershift in 4.13.
It might be good to follow up and remove the job if possible.

2024-05-07 19:30 UTC, JacobTanenbaum commented on go-controller/pkg/ovnwebhook/podadmission.go
> +	annotations       map[string]checkPodAnnot
done

2024-05-07 19:30 UTC, JacobTanenbaum commented on go-controller/pkg/ovnwebhook/podadmission_test.go
> +		{
done

2024-05-07 19:30 UTC, JacobTanenbaum commented on go-controller/pkg/ovnwebhook/podadmission_test.go
> +		/*
done

2024-05-09 14:01 UTC, JacobTanenbaum commented
/test e2e-aws-ovn-windows

2024-05-09 15:10 UTC, JacobTanenbaum commented on go-controller/pkg/ovnwebhook/podadmission.go
> +	if podAdmission == nil {
done

2024-05-09 15:11 UTC, JacobTanenbaum commented
/test e2e-aws-ovn-windows

2024-05-10 13:48 UTC, JacobTanenbaum commented
/test e2e-aws-ovn-windows
It does not seem to be caused by my PR as my change should not change the code running on the windows nodes

2024-05-10 14:37 UTC, kyrtapz commented
/lgtm

2024-05-15 11:38 UTC, kyrtapz commented
/lgtm
/retest

2024-05-16 09:37 UTC, tssurya commented on go-controller/go.mod
> +	k8s.io/kubernetes v0.0.0-00010101000000-000000000000
why is this not 1.26 ? what's with the 000's?

2024-05-16 09:37 UTC, tssurya commented on contrib/kind.sh
> +  if [ "${OVN_ENABLE_OVNKUBE_IDENTITY}" == true ]; then
hmm in commit https://github.com/ovn-org/ovn-kubernetes/pull/3830/commits/7dc48048a346f175772fe5c2839b083f7a20c597#diff-74a1a8552feeb3203caa0b2f9cc5c9c0eeca76451e37f1a61865c598b3247444R977 I don't see the apply being done in `install_ovn`, for nonIC on 4.14 are we doing it in a different way? I see the apply being done in all the zone related functions..

2024-05-16 09:37 UTC, tssurya commented on dist/images/ovnkube.sh
> +    #   ovnkube-cluster-manager service account - required for multi-homing
there is no cluster-manager in 4.13

2024-05-16 09:37 UTC, tssurya commented on dist/images/ovnkube.sh
> +    --extra-allowed-user="system:serviceaccount:ovn-kubernetes:ovnkube-node" \
is node supposed to be included? I see https://github.com/ovn-org/ovn-kubernetes/pull/3830/commits/7dc48048a346f175772fe5c2839b083f7a20c597#diff-ea48eab674fe05348e580125fccb19b775e0fd6f6a2d28a2dab5fb382590a16aR1031 doesn't have it..

2024-05-16 09:37 UTC, tssurya commented on dist/templates/ovnkube-node.yaml.j2
missing https://github.com/ovn-org/ovn-kubernetes/pull/3830/commits/7dc48048a346f175772fe5c2839b083f7a20c597#diff-7f12cbdb07b28405a074de7ba6f2720087b020d9cd4ad0b3107fbda3d277a192L31 not that it matters but was standing out as being intentionally left out as part of backport

2024-05-16 09:37 UTC, tssurya commented on go-controller/Makefile
why is https://github.com/ovn-org/ovn-kubernetes/pull/3830/commits/7dc48048a346f175772fe5c2839b083f7a20c597#diff-1665ad572262e64ebefe064287cd9c3759b39328a15d4efcdb0cb3800a15cc40R12 missing? again doesn't matter but curious why backport leaves out a few pieces..

2024-05-16 09:37 UTC, tssurya commented on go-controller/cmd/ovnkube-identity/ovnkubeidentity.go
self-note: stopping review at commit4; at this file. Will come back for round2 (had to cut this in the middle for a higher priority interruption/distraction)

2024-05-16 13:30 UTC, JacobTanenbaum commented on contrib/kind.sh
> +  if [ "${OVN_ENABLE_OVNKUBE_IDENTITY}" == true ]; then
in 4.14 non-ic this is enabled install_ovn() calls install_ovn_global_zone which does the check and application of the yaml. in 4.13 there are no zone functions so I moved the check here.

2024-05-16 14:29 UTC, JacobTanenbaum commented on go-controller/cmd/ovnkube/ovnkube.go
> +		if err := util.StartNodeCertificateManager(ctx.Context, ovnKubeStartWg, &config.Kubernetes); err != nil {
we do need to start the cert-manager in the hybrid overlay node, done

2024-05-16 14:29 UTC, JacobTanenbaum commented on go-controller/go.mod
> +	k8s.io/kubernetes v0.0.0-00010101000000-000000000000
didn't realize it did that, fixed

2024-05-16 14:30 UTC, JacobTanenbaum commented on dist/images/ovnkube.sh
> +    #   ovnkube-cluster-manager service account - required for multi-homing
removed the comment

2024-05-16 14:30 UTC, JacobTanenbaum commented on dist/images/ovnkube.sh
> +    --extra-allowed-user="system:serviceaccount:ovn-kubernetes:ovnkube-node" \
removed the extra allowed user, thought I needed it for hybrid overlay to self post the DRMAC and DRIP, does not seem to need it

2024-05-16 14:34 UTC, JacobTanenbaum commented on go-controller/Makefile
the comment you refer do does get added in at commit 4f68a49ed55e13dbd164f633723084c89b37baf1 (current hash, here is the commit title "OVN-Kubernetes Node Identity docs" if future rebasing messes with the hash  )

2024-05-16 18:26 UTC, JacobTanenbaum commented
looks like a series of errors 
ci/prow/4.13-upgrade-from-stable-4.12-e2e-aws-ovn-upgrade looks like it was effected by [OCP-33005](https://issues.redhat.com/browse/OCPBUGS-33005)
ci/prow/4.13-upgrade-from-stable-4.12-local-gateway-e2e-aws-ovn-upgrade: failed to find the image registry 
ci/prow/e2e-aws-ovn-upgrade looks like it might have hit [OCPBUGS-30899](https://issues.redhat.com//browse/OCPBUGS-30899)

/retest-required

2024-05-20 17:32 UTC, JacobTanenbaum commented
/retest-required

2024-05-21 14:36 UTC, JacobTanenbaum commented
/retest-required

2024-05-22 09:50 UTC, tssurya commented on contrib/kind.sh
> +  if [ "${OVN_ENABLE_OVNKUBE_IDENTITY}" == true ]; then
ack I see thanks Jake. resolving this

2024-05-22 09:51 UTC, tssurya commented on go-controller/Makefile
ah ack makes sense

2024-05-22 10:09 UTC, tssurya commented on go-controller/pkg/ovnwebhook/podadmission.go
> +var interconnectPodAnnotations = map[string]checkPodAnnot{
I still see the interconnect code here in this commit; was it removed in another commit? AH I see you did it in https://github.com/openshift/ovn-kubernetes/pull/2053/commits/a0dbbe12b219ea32f917d8298feb407a73c6aee3 might recommend squashing for preserving history and so that each commit standalone makes sense,

2024-05-22 10:09 UTC, tssurya commented on go-controller/pkg/ovnwebhook/podadmission.go
> +		annotationKeys:    sets.New[string](maps.Keys(interconnectPodAnnotations)...),
this is removed https://github.com/openshift/ovn-kubernetes/pull/2053/commits/a0dbbe12b219ea32f917d8298feb407a73c6aee3

2024-05-22 10:09 UTC, tssurya commented on .github/workflows/docker.yml
commit4 and commit 11 are done

2024-05-22 10:58 UTC, tssurya requested changes
What about https://github.com/ovn-org/ovn-kubernetes/pull/3929/commits/44d8d921500155b76c9e2e56fbc2135ac612ead6 this commit do we need to bring that in?

2024-05-22 11:01 UTC, tssurya commented
finished reviewing all commits @JacobTanenbaum if you can PTAL my comments above we can circle back on merging this asap.

I'd feel a lot better running payload testing for this PR and involving pre-merge testing for this feature with QE. Have we notified QE about https://issues.redhat.com/browse/SDN-4186 ? I don't consider this a bugfix backport; it should be treated like any other feature.

2024-05-23 15:39 UTC, JacobTanenbaum commented on contrib/kind.sh
> +  if [ "${OVN_ENABLE_OVNKUBE_IDENTITY}" == true ]; then
:+1:

2024-05-23 15:42 UTC, JacobTanenbaum commented
> What about [ovn-org/ovn-kubernetes@44d8d92](https://github.com/ovn-org/ovn-kubernetes/commit/44d8d921500155b76c9e2e56fbc2135ac612ead6) this commit do we need to bring that in?

In the description I mention that the annotation does not exist in 4.13 so bringing that commit in is not possible or required

2024-05-23 15:47 UTC, JacobTanenbaum commented on go-controller/cmd/ovnkube-identity/ovnkubeidentity.go
@kyrtapz correct me if I am wrong, but this is a symptom of updating. When updating both the old and new version of the webhook are running for a short time. The webhook that services requests is randomly selected during that short window and if the version of the webhook selected is not running the podAdmission webhook the 4.14 upgrade can fail because the 4.14 ovnkube-nodes cannot start.

2024-05-23 15:48 UTC, JacobTanenbaum commented
/payload 4.13 ci blocking
/payload 4.13 nightly blocking

2024-05-23 15:56 UTC, kyrtapz commented on go-controller/cmd/ovnkube-identity/ovnkubeidentity.go
That's correct. During an upgrade we are running both the old and the new webhook when the daemonset is updating. Jacob discovered this while testing 4.13(with this and CNO PR) to a 4.14 release.

2024-05-23 16:05 UTC, JacobTanenbaum commented on go-controller/cmd/ovnkube-identity/ovnkubeidentity.go
> +	if len(cliCfg.podAdmissionConditions) > 1 {
this is changed to run tun the podAdmission plugin all the time see comment https://github.com/openshift/ovn-kubernetes/pull/2053#discussion_r1611937689

2024-05-23 16:08 UTC, asood-rh commented
/label cherry-pick-approved

2024-05-23 16:15 UTC, asood-rh commented
/label cherry-pick-approved cancel

2024-05-23 16:27 UTC, asood-rh commented
/cherry-pick-approved cancel

2024-05-23 20:22 UTC, asood-rh commented
/ocpbugs cc-qa

2024-05-29 14:36 UTC, JacobTanenbaum commented
/payload 4.13 ci blocking
/payload 4.13 nightly blocking
/retest-required

2024-05-29 15:23 UTC, tssurya commented
/test e2e-aws-ovn-hypershift

2024-05-29 23:46 UTC, asood-rh commented
Pre merge testing passed on the PR, details of testing in JIRA.

/label qe-approved

2024-05-30 09:11 UTC, tssurya commented
LGTM, https://pr-payload-tests.ci.openshift.org/runs/ci/df940820-1dc8-11ef-896d-73ecea9b789d-0 looks green and 

https://pr-payload-tests.ci.openshift.org/runs/ci/df940820-1dc8-11ef-896d-73ecea9b789d-1 looks totally RED. I am taking a risk and merging this since without CNO we are not enabling this feature anyways, please re-do payloads on the CNO PR

2024-05-30 09:12 UTC, tssurya commented
/lgtm
/label backport-risk-assessed

2024-05-30 09:12 UTC, tssurya commented
/jira refresh

2024-05-30 09:13 UTC, tssurya commented
@JacobTanenbaum : you need a bug for this please fix the jira labels, I have added lgtm, risk-assessed so I think that's it from my side for this PR

2024-05-30 14:18 UTC, JacobTanenbaum commented
/jira refresh

2024-05-30 14:21 UTC, merged