OCPBUGS-24007: Remove unnecessary rhel8 build layer
openshift/ovn-kubernetes pull request #2083
Opened 2024-02-26 17:34 UTC by bpickard22

resolves OCPBUGS-24007

For upgrades from 4.12 to 4.13 on fips we needed to include both a rhel8 and 9 binary based ovn-k container image, this is not needed on 4.14+ clusters

2024-02-26 17:34 UTC, bpickard22 commented
/jira refresh

2024-02-26 17:40 UTC, tssurya commented
/assign @tssurya

2024-02-27 16:01 UTC, bpickard22 commented
/retest-required

2024-03-06 17:46 UTC, tssurya requested changes

2024-03-06 17:46 UTC, tssurya commented on Dockerfile
>  # Copy RHEL-8 and RHEL-9 shim binaries where the CNO's ovnkube-node container startup script can find them
nit: fix comment? no more RHEL-8

2024-03-06 17:46 UTC, tssurya commented on Dockerfile
>  # Copy RHEL-8 and RHEL-9 shim binaries where the CNO's ovnkube-node container startup script can find them
rest look ok based on https://github.com/openshift/ovn-kubernetes/pull/1748/files

2024-03-25 18:25 UTC, tssurya approved these changes
/lgtm
/approve

2024-03-27 18:29 UTC, merged

2024-03-27 18:36 UTC, bpickard22 commented
/cherry-pick release-4.15

2024-04-01 01:38 UTC, sdodson commented
ovn-controller now crashloops on RHEL8 workers which remain supported
```
/2024-03-29T20:41:34.082252221Z + rhelmajor=8
2024-03-29T20:41:34.082252221Z + sourcedir=/usr/libexec/cni/
2024-03-29T20:41:34.082269221Z + case "${rhelmajor}" in
2024-03-29T20:41:34.082269221Z + sourcedir=/usr/libexec/cni/rhel8
2024-03-29T20:41:34.082276361Z + cp -f /usr/libexec/cni/rhel8/ovn-k8s-cni-overlay /cni-bin-dir/
2024-03-29T20:41:34.083575440Z cp: cannot stat '/usr/libexec/cni/rhel8/ovn-k8s-cni-overlay': No such file or directory
```

2024-04-01 01:46 UTC, sdodson commented
https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-workers-rhel8 shows that the first failing job includes a nightly after this change made it in. The last successful job actually used a build from March 25th.