Downstream Merge Oct 31st 2024
openshift/ovn-kubernetes pull request #2334
Opened 2024-10-31 19:27 UTC by jluhrsen

#### What this PR does and why is it needed

#### Which issue(s) this PR fixes

Fixes #

#### Special notes for reviewers

#### How to verify it

#### Details to documentation updates

#### Description for the changelog

#### Does this PR introduce a user-facing change?

```release-note

```

2024-10-31 21:22 UTC, trozet requested changes

2024-10-31 21:22 UTC, trozet commented on go-controller/pkg/node/gateway_localnet.go
> -	// OCP HACK -- block MCS ports https://github.com/openshift/ovn-kubernetes/pull/170
we need to preserve these OCP hacks

2024-11-01 08:50 UTC, tssurya commented
@jluhrsen please tag the team on slack so that they can add their bugs
when you open ds merges please announce on UDN-Channel so that everyone is aware, specially tag udn-qe
I have outlined the steps here: https://issues.redhat.com/browse/SDN-5297?focusedId=25896306&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25896306

another thing to note this merge shouldn't go in until 1 or two green nightly payload images are released with our previous downstream merge

2024-11-01 09:08 UTC, tssurya commented
/retest

2024-11-01 13:48 UTC, trozet commented on go-controller/pkg/node/gateway_localnet.go
> -	// OCP HACK -- block MCS ports https://github.com/openshift/ovn-kubernetes/pull/170
Actually, this is correct to remove this...because now shared and local gw share the same code, and we already call this same code in newGateway, which is used by both modes:

```
	case config.GatewayModeLocal, config.GatewayModeShared:
		klog.Info("Preparing Gateway")
		gw, err = newGateway(nc.name, subnets, gatewayNextHops, gatewayIntf, egressGWInterface, ifAddrs, nodeAnnotator,
			managementPortConfig, nc.Kube, nc.watchFactory, nc.routeManager, nc.nadController, config.Gateway.Mode)
```

2024-11-01 13:50 UTC, trozet commented on go-controller/pkg/node/gateway_localnet.go
> -	// OCP HACK -- block MCS ports https://github.com/openshift/ovn-kubernetes/pull/170
https://github.com/openshift/ovn-kubernetes/pull/2334/files#diff-d3aa58d9b58a0a09264f072df46ab01d0501eb508c4656411ae2dc1ac68fb3c4R1946

2024-11-01 13:51 UTC, trozet commented
/retest

2024-11-01 18:49 UTC, jluhrsen commented
> @jluhrsen please tag the team on slack so that they can add their bugs (For UDN the services bug ricky had should be tagged) when you open ds merges please announce on UDN-Channel so that everyone is aware, specially tag udn-qe I have outlined the steps here: https://issues.redhat.com/browse/SDN-5297?focusedId=25896306&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25896306
> 
> another thing to note this merge shouldn't go in until 1 or two green nightly payload images are released with our previous downstream merge

ok @tssurya, thank you for doing the announcement this time.

2024-11-01 18:49 UTC, jluhrsen commented on go-controller/pkg/node/gateway_localnet.go
> -	// OCP HACK -- block MCS ports https://github.com/openshift/ovn-kubernetes/pull/170
ack

2024-11-01 18:50 UTC, jluhrsen commented
/retest

2024-11-02 14:31 UTC, trozet commented
/retest

2024-11-02 19:27 UTC, jluhrsen commented
/retest

2024-11-04 11:39 UTC, tssurya commented
/payload 4.18 ci

2024-11-04 11:39 UTC, tssurya commented
/payload ci 4.18

2024-11-04 11:41 UTC, tssurya commented
/payload 4.18 ci blocking

2024-11-04 11:48 UTC, tssurya commented
@jluhrsen how was this merge opened ? asking because the last commit title looks different:
usually we keep the commit message as "Merge remote-tracking branch 'origin/master' into merge-10-8-24" which is the signal commit of the merge ending... Did you manually edit the commit message is that why it looks different? just making sure it was intentional change..

2024-11-04 11:59 UTC, tssurya commented on go-controller/pkg/node/gateway_localnet.go
> -	// OCP HACK -- block MCS ports https://github.com/openshift/ovn-kubernetes/pull/170
hmm are these conflicts/downstream merge changes outlined anywhere? I assume it was not a clean merge right? cc @ricky-rav for your bits

2024-11-04 15:54 UTC, ricky-rav commented on go-controller/pkg/node/gateway_localnet.go
> -	// OCP HACK -- block MCS ports https://github.com/openshift/ovn-kubernetes/pull/170
Here we should restore the OCP hack that calls `insertMCSBlockIptRules()`. We can add it to `initLocalGateway` in pkg/node/gateway_localnet.go

2024-11-04 16:00 UTC, ricky-rav commented on go-controller/pkg/node/gateway_localnet.go
> -	// OCP HACK -- block MCS ports https://github.com/openshift/ovn-kubernetes/pull/170
Looks OK to me! I see only one OCP hack being affected here, which is the one that calls `insertMCSBlockIptRules` in both `newLocalGateway` and `newSharedGateway`. We kept it in the latter, which I renamed `newGateway`, so all good from my side.

2024-11-04 18:06 UTC, jluhrsen commented
> @jluhrsen how was this merge opened ? asking because the last commit title looks different: usually we keep the commit message as "Merge remote-tracking branch 'origin/master' into merge-10-8-24" which is the signal commit of the merge ending... Did you manually edit the commit message is that why it looks different? just making sure it was intentional change..

yes, sorry @tssurya, I manually edited the commit message. I can change it back if it's important and I will make sure to not do that again.

2024-11-04 18:13 UTC, jluhrsen commented
> another thing to note this merge shouldn't go in until 1 or two green nightly payload images are released with our previous downstream merge

the payload that our previous merge was included is [this one](https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.18.0-0.nightly/release/4.18.0-0.nightly-2024-10-31-233806) and it passed. the next payload also passed. However, the five following all failed and there hasn't been a passing payload since then yet. I'll make sure payloads are passing again before we look at merging this one.

https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/#4.18.0-0.nightly

2024-11-04 18:15 UTC, jluhrsen commented
> @tssurya: trigger 4 job(s) of type blocking for the ci release of OCP 4.18
> 
> * periodic-ci-openshift-release-master-ci-4.18-upgrade-from-stable-4.17-e2e-aws-ovn-upgrade
> * periodic-ci-openshift-release-master-ci-4.18-upgrade-from-stable-4.17-e2e-azure-ovn-upgrade
> * periodic-ci-openshift-release-master-ci-4.18-e2e-gcp-ovn-upgrade
> * periodic-ci-openshift-hypershift-release-4.18-periodics-e2e-aws-ovn
> 
> See details on https://pr-payload-tests.ci.openshift.org/runs/ci/b09c7330-9aa1-11ef-9436-4344bec35709-0

This is showing as green, although when you drill down in to the actual jobs that are run it's interesting to
see how many failed jobs we put up with. :(

2024-11-04 18:28 UTC, jluhrsen commented on go-controller/pkg/node/gateway_localnet.go
> -	// OCP HACK -- block MCS ports https://github.com/openshift/ovn-kubernetes/pull/170
@tssurya , correct. there was one merge conflict in go-controller/pkg/node/gateway_localnet.go which looked like [this](https://github.com/jluhrsen/ovn-kubernetes-1/blob/merge-10-31-24.tmp/go-controller/pkg/node/gateway_localnet.go). TBH, I am not up to speed on these changes and just went with what we have in u/s master for that file which passed the build and tests locally.

We are good right?

I honestly don't understand how the conflict can occur if we are essentially just syncing the same commits from u/s to d/s 😕

2024-11-04 18:54 UTC, tssurya commented
> > @jluhrsen how was this merge opened ? asking because the last commit title looks different: usually we keep the commit message as "Merge remote-tracking branch 'origin/master' into merge-10-8-24" which is the signal commit of the merge ending... Did you manually edit the commit message is that why it looks different? just making sure it was intentional change..
> 
> yes, sorry @tssurya, I manually edited the commit message. I can change it back if it's important and I will make sure to not do that again.

no I'm fine with it was curious that's all all good

2024-11-05 12:25 UTC, tssurya commented
hypershift and microshift are failing outside of that this PR seems ready to go!
@trozet wanna approve ? or @ricky-rav or anyone who has a commit in this PR?
@jluhrsen is there anything else blocking this PR from merging?

2024-11-05 15:09 UTC, merged