Bug 1882694: Pin OVS to latest 4.4.22 RPM version
openshift/ovn-kubernetes pull request #290
Opened 2020-09-25 12:17 UTC by alexanderConstantinescu

As done in https://github.com/openshift/ovn-kubernetes/pull/284 but for OVS

/assign @dcbw @trozet 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

2020-09-25 12:20 UTC, alexanderConstantinescu commented
/retitle Bug 1882694: [release-4.5] Pin OVS to latest 4.4.22 RPM version

2020-09-25 20:47 UTC, trozet requested changes

2020-09-25 20:47 UTC, trozet commented on Dockerfile
> +	yum install -y --setopt=tsflags=nodocs --setopt=skip_missing_names_on_install=False "openvswitch2.13 >= 2.13.0-46.el7fdp" "openvswitch2.13-devel == 2.13.0-46.el7fdp" && \
you have  >= here, shoudln't that be == ?

2020-09-28 08:35 UTC, alexanderConstantinescu commented on Dockerfile
> +	yum install -y --setopt=tsflags=nodocs --setopt=skip_missing_names_on_install=False "openvswitch2.13 >= 2.13.0-46.el7fdp" "openvswitch2.13-devel == 2.13.0-46.el7fdp" && \
It should. Thanks for spotting that!

2020-09-28 08:35 UTC, alexanderConstantinescu commented
/bugzilla refresh

2020-10-14 01:49 UTC, dcbw commented
/retest

2020-10-14 06:55 UTC, alexanderConstantinescu commented
> /retest

How about an `/lgtm` and `/approve` and we let the bot do that for us? :smiling_imp:

2020-11-19 14:19 UTC, trozet commented
/lgtm

2020-12-01 21:51 UTC, knobunc commented
/approve

2020-12-01 21:58 UTC, knobunc commented
/cherrypick 4.4.z

2020-12-01 22:22 UTC, alexanderConstantinescu commented
/hold

this PR has been on the back-burner for too long. OVS on 4.4.z and 4.5.z have been bumped to 2.13.0-50.el7fdp. And moreover, I this PR needs to bump OVS to 2.13.0-63.el7fdp as to get the CVE fix in directly. But first we will need https://github.com/openshift/ovn-kubernetes/pull/358 to get in and have master and 4.6 on that version

2021-01-21 20:54 UTC, crawford commented
@alexanderConstantinescu any update?

2021-01-26 14:46 UTC, alexanderConstantinescu commented
/hold cancel

2021-01-26 17:00 UTC, trozet commented
/lgtm

2021-01-28 00:41 UTC, merged