Klog v2
openshift/ovn-kubernetes pull request #315
Opened 2020-10-20 13:26 UTC by tfherbert

fixes #1886062

k8s.io/klog moved to v2 in client-go and frieds. The operator does not use v2 yet and hence, we lose one half of the logging output (v2).

**- Description for the changelog**
Logging is broken due to mix of k8s.io/klog v1 and v3

2020-10-22 10:51 UTC, juanluisvaladas requested changes
I see 29 commits unrelated to this change, is that a deliberate rebase? If so it should probably be documented in the PR description.

2020-10-22 10:51 UTC, juanluisvaladas commented on go-controller/vendor/k8s.io/apimachinery/pkg/api/meta/meta.go
> +	"k8s.io/klog/v2"
You can't do this.
This will be overwritten by go mod vendor (and is replaced in the following commit go mod vendor)

I think in go.mod you can do instead of `replace github.com/ebay/go-ovn v0.1.0 => github.com/ebay/go-ovn v0.1.1-0.20200810162212-30abed5fb968` you can do:

```
replace (
	github.com/ebay/go-ovn v0.1.0 => github.com/ebay/go-ovn v0.1.1-0.20200810162212-30abed5fb968
	k8s.io/klog => k8s.io/klog/v2 v2.3.0
)
```

And that would force klog v2. I  haven't actually tested this.

2020-10-22 14:43 UTC, tfherbert commented on go-controller/vendor/k8s.io/apimachinery/pkg/api/meta/meta.go
> +	"k8s.io/klog/v2"
No, my fork and picked up the "extra" commits which should now be in master. The plan is for this PR to be merged into master and then later cherry-picked into 4.6.z.  Maybe I should rebase and generate new clean PR.

As for /v2 that seemed to work and is consistent with other projects merged into openshift. I had to run go mod vendor to suck in klog/v2 into vendor and it seemed to work but it seems messy to me.

2020-10-22 16:10 UTC, tfherbert commented
Converting this PR to draft for documentation.

2020-12-08 15:00 UTC, tfherbert commented
This is superceded by PR #1817 to ovn.org/ovn-kubernetes already merged

2020-12-08 15:00 UTC, closed without merging