Fix broken `make check` on master
openshift/ovn-kubernetes pull request #347
Opened 2020-11-16 17:34 UTC by alexanderConstantinescu

The release-4.6 branch are broken when running the command `make check`.
This commit fixes the build. 

Tomorrow I am going to work on having `make check` be gating on release-4.6 and master (similar to `/test unit` on openshift/sdn) as to not have to do this again. 

/assign @trozet 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

2020-11-16 17:45 UTC, alexanderConstantinescu commented
/retitle Bug 1898269: Fix broken `make check` on master

2020-11-16 17:46 UTC, alexanderConstantinescu commented
/retitle Bug 1898269: Fix broken make check on 4.6

2020-11-16 18:52 UTC, abhat commented
@alexanderConstantinescu I already had #329 to fix the same issue. I can close mine if you would like.

2020-11-19 15:20 UTC, trozet requested changes

2020-11-19 15:20 UTC, trozet commented on go-controller/pkg/ovn/master_test.go
> -	"net"
dont move this

2020-11-19 15:26 UTC, alexanderConstantinescu commented on go-controller/pkg/ovn/master_test.go
> -	"net"
Why? Go standard library imports should be declared first right (according to the convention), so it's wrong today. Is it just as to not increase the diff?

2020-11-19 17:04 UTC, trozet commented on go-controller/pkg/ovn/master_test.go
> -	"net"
it can crate conflicts when we merge later downstream. If its wrong fix it in upstream then downstream

2020-12-01 15:06 UTC, dcbw commented
/lgtm
/approve
/retest

2020-12-01 17:05 UTC, dcbw commented
/override ci/prow/e2e-metal-ipi-ovn-dualstack

2020-12-01 17:47 UTC, dcbw commented
/retest

2020-12-01 18:49 UTC, dcbw commented
/retest

2020-12-01 20:56 UTC, dcbw commented
/retest

2020-12-01 21:56 UTC, dcbw commented
/retest
`msg="Error: Error when reading or editing ComputeRegionBackendService \"projects/openshift-gce-devel-ci/regions/us-east1/backendServices/ci-op-iz744ttd-9e101-7qd2j-api-internal\": googleapi: Error 403: Quota exceeded for quota group 'ReadGroup' and limit 'Read requests per 100 seconds' of service 'compute.googleapis.com' for consumer 'project_number:1053217076791'., rateLimitExceeded`

2020-12-01 21:57 UTC, dcbw commented
/retest

2020-12-02 02:12 UTC, dcbw commented
/retest

2020-12-02 15:24 UTC, merged