Merge 2021-07-21
openshift/ovn-kubernetes pull request #616
Opened 2021-07-21 15:45 UTC by alexanderConstantinescu

/assign @dcbw @trozet 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

2021-07-21 22:05 UTC, dcbw commented
/retest

2021-07-21 22:13 UTC, trozet requested changes
/hold

2021-07-21 22:13 UTC, trozet commented on go-controller/pkg/node/gateway_localnet.go
> +		gwBridge, _, err := gatewayInitInternal(
merge conflict resolution looks right to me

2021-07-21 22:13 UTC, trozet commented on go-controller/pkg/node/gateway_shared_intf.go
>  	gw.readyFunc = func() (bool, error) {
I don't think this is right, it should be:
```
	if exGwBridge != nil {
		gw.readyFunc = func() (bool, error) {
			ready, err := gatewayReady(gwBridge.patchPort)
			if err != nil {
				return false, err
			}
			exGWReady, err := gatewayReady(exGwBridge.patchPort)
			if err != nil {
				return false, err
			}
			return ready && exGWReady, nil
		}
	} else {
		gw.readyFunc = func() (bool, error) {
			return gatewayReady(gwBridge.patchPort)
		}
	}
```
https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/node/gateway_shared_intf.go#L580

@fedepaol can confirm

2021-07-21 22:17 UTC, trozet commented on go-controller/pkg/node/gateway_localnet.go
>  			return gatewayReady(patchPort)
actually this isnt right:
https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/node/gateway_localnet.go#L69

2021-07-21 22:29 UTC, trozet commented
@alexanderConstantinescu in the interest of time I started another one with what I think is the right merge conflict resolution:
https://github.com/openshift/ovn-kubernetes/pull/618

https://github.com/openshift/ovn-kubernetes/pull/618/files#diff-32663df3b1d1ffb0ecde35d8f44b6e4e2ae451b5712eaa054a1ee99fc07918fb

https://github.com/openshift/ovn-kubernetes/pull/618/files#diff-d3aa58d9b58a0a09264f072df46ab01d0501eb508c4656411ae2dc1ac68fb3c4R581

2021-07-22 07:42 UTC, fedepaol commented on go-controller/pkg/node/gateway_shared_intf.go
>  	gw.readyFunc = func() (bool, error) {
Yes I confirm

2021-07-22 07:47 UTC, closed without merging