Reconnect to nbdb if there is transaction error
openshift/ovn-kubernetes pull request #717
Opened 2021-09-03 19:48 UTC by tssurya

Under heavy load, monitor gets dropped silently and we stop receiving `update` messages from ovsdbserver. This leads to stale cache and inconsistency with what's in the DB leading to transaction errors. While this is originally a ovsdbserver bug, a workwround fix here would be to trigger reconnect to recreate the monitor and start receiving update messages, when a transaction error occurs.

Co-Authored-By: trozet@redhat.com

2021-09-04 00:34 UTC, trozet requested changes

2021-09-04 00:34 UTC, trozet commented on go-controller/vendor/github.com/ebay/go-ovn/client.go
> +	tranmutex    sync.Mutex
use an RWMutex, and call Lock like you are in 362 thats good. But you need to RLock in transact. If you dont then the mutex isnt really doing anything. The purpose of adding the mutex back here is so that we avoid issuing a transaction while the client could be nil:
https://github.com/openshift/ovn-kubernetes/pull/717/files

That would cause a panic and crash ovnkube. On the other hand if the client is not nil, but closed, that will simply return an error "error: connection is shut down"

2021-09-04 00:34 UTC, trozet commented on go-controller/vendor/github.com/ebay/go-ovn/client.go
> +		c.tranmutex.Lock()
move this under line 364 so we get the log message before we lock the mutex

2021-09-04 00:34 UTC, trozet commented on go-controller/vendor/github.com/ebay/go-ovn/ovnimp.go
> +			odbi.Close()
add 
```
c.tranMutex.RLock() 
defer c.tranMutexRUnlock()
```
at the start of this transact function

2021-09-04 00:36 UTC, trozet commented
you also need to pull in my commit for monitor_cancel support:
https://github.com/eBay/libovsdb/pull/41

2021-09-04 00:38 UTC, trozet commented
/retitle Bug 1998614: Ensure client handling of canceled/dropped OVSDB monitor

2021-09-04 00:44 UTC, trozet commented on go-controller/vendor/github.com/ebay/go-ovn/client.go
> +	tranmutex    sync.Mutex
https://github.com/openshift/ovn-kubernetes/blob/41ad158235fcb290bab580a3bade8b521c732377/go-controller/vendor/github.com/ebay/go-ovn/client.go#L302

2021-09-04 00:46 UTC, trozet commented
/bugzilla refresh

2021-09-04 14:00 UTC, dcbw commented on go-controller/vendor/github.com/ebay/go-ovn/ovnimp.go
> +			odbi.Close()
@trozet FWIW Surya and I decided we do not need to protect any other uses of `c.client` (GetSchema(), Close()) in 4.7.

But @tssurya since this PR is for master/4.9, we do need to protect Close() (because updateSslKeyPair() calls Close()) and we also need to split GetSchema() into a locked and unlocked variant because deleteChassis() calls it.

2021-09-04 14:13 UTC, trozet commented on go-controller/vendor/github.com/ebay/go-ovn/ovnimp.go
> +			odbi.Close()
good catch. We can backport this protection as well for Close and GetSchema just in case. So Close can use tranMutex.Lock() and tranMutex.RUnlock() should be used in GetSchema(). Like dcbw suggested we need internal/external function because Transact will already have the lock, so it can just call ```c.client.Disconnect()```

2021-09-04 22:00 UTC, tssurya commented on go-controller/vendor/github.com/ebay/go-ovn/client.go
> +		c.tranmutex.Lock()
ack. done.

2021-09-04 22:14 UTC, tssurya commented on go-controller/vendor/github.com/ebay/go-ovn/client.go
> +	tranmutex    sync.Mutex
done.

2021-09-04 23:12 UTC, tssurya commented
> you also need to pull in my commit for monitor_cancel support:
> [eBay/libovsdb#41](https://github.com/eBay/libovsdb/pull/41)

done!

2021-09-05 01:17 UTC, trozet commented
/lgtm

thanks @tssurya !

2021-09-05 01:18 UTC, trozet commented
/retest

2021-09-05 02:52 UTC, trozet commented
/retest-required

2021-09-05 06:44 UTC, trozet commented
/retest

2021-09-05 13:29 UTC, dcbw commented
/lgtm

2021-09-05 16:35 UTC, merged

2021-09-14 06:18 UTC, tssurya commented
/cherry-pick release-4.8