Bug 2022042: Avoid stale annotations by re-subscribing to netlink
openshift/ovn-kubernetes pull request #828
Opened 2021-11-10 20:39 UTC by flavio-fernandes

This PR includes the fixed needed for bug 2022042, including its dependencies.

Needed commits were cherry picked from trozet:fix_downstream_merge.

2021-11-10 20:42 UTC, flavio-fernandes commented on go-controller/pkg/node/gateway_shared_intf.go
> +		//TODO(flaviof): line below not part of 4.9; only 4.10.
@trozet @Kyrtapz : does look right to you?

2021-11-10 20:43 UTC, trozet commented
/retitle Bug 2022042: [4.9z] Avoid stale annotations by re-subscribing to netlink

2021-11-10 20:59 UTC, trozet commented on go-controller/pkg/node/gateway_shared_intf.go
> +		//TODO(flaviof): line below not part of 4.9; only 4.10.
That code was originating from external traffic policy that @astoycos did:
https://github.com/ovn-org/ovn-kubernetes/commit/bd7a7f6e8ee140a9988c81e7fa438e95826f39e7#diff-d3aa58d9b58a0a09264f072df46ab01d0501eb508c4656411ae2dc1ac68fb3c4R1078

I thought that was supposed to be in 4.9...

2021-11-10 21:05 UTC, trozet commented on go-controller/pkg/node/gateway_shared_intf.go
> +		//TODO(flaviof): line below not part of 4.9; only 4.10.
Looks like it was only merged into 4.10:
https://bugzilla.redhat.com/show_bug.cgi?id=1903408

@astoycos was the plan to backport ETP into 4.9z?

2021-11-10 21:07 UTC, trozet requested changes

2021-11-10 21:07 UTC, trozet commented on go-controller/pkg/node/gateway_shared_intf.go
> +		//TODO(flaviof): line below not part of 4.9; only 4.10.
@flavio-fernandes for now you will uncomment line 633 or else we wont have an address manager because you removed it in gateway_init.go

2021-11-10 22:55 UTC, flavio-fernandes commented
/assign @Kyrtapz

2021-11-11 00:41 UTC, flavio-fernandes commented
/bugzilla refresh

2021-11-11 21:13 UTC, flavio-fernandes commented
/retest

2021-11-13 02:55 UTC, trozet commented
/retest
/lgtm
/label backport-risk-assessed

2021-11-15 15:56 UTC, abhat commented
/bugzilla refresh

2021-11-16 19:56 UTC, flavio-fernandes commented
/retest

2021-11-16 21:29 UTC, abhat commented
/test images

2021-11-17 00:37 UTC, flavio-fernandes commented
/retest

2021-11-17 01:26 UTC, trozet commented
/retest

2021-11-17 03:22 UTC, abhat commented
/retest

2021-11-17 08:07 UTC, huiran0826 commented
/lgtm

2021-11-18 04:09 UTC, trozet commented
/label bugzilla/valid-bug

2021-11-18 13:12 UTC, knobunc commented
Adding valid-bug per slack agreement that since there was a major rewrite in 4.10 the code there is sufficiently different that it doesn't help validate this.

2021-11-18 14:27 UTC, mffiedler commented
/label cherry-pick-approved

2021-11-18 14:39 UTC, mffiedler commented
Verified per https://bugzilla.redhat.com/show_bug.cgi?id=2022042#c2

/label qe-approved
/label lgtm

2021-11-18 17:34 UTC, abhat commented
/test e2e-metal-ipi-ovn-ipv6

2021-11-19 00:55 UTC, merged