Bug 2022043: [4.8z] Avoid stale annotations by re-subscribing to netlink
openshift/ovn-kubernetes pull request #829
Opened 2021-11-10 22:22 UTC by flavio-fernandes

This PR includes the fixed needed for bug 2022043, including its dependencies.

2021-11-11 01:05 UTC, flavio-fernandes commented
/bugzilla refresh

2021-11-11 01:05 UTC, flavio-fernandes commented
/assign @Kyrtapz

2021-11-11 01:13 UTC, flavio-fernandes reviewed
@Kyrtapz @trozet PTAL!

2021-11-11 01:13 UTC, flavio-fernandes commented on go-controller/pkg/kube/annotator.go
> +	// TODO(flaviof): need to resolve this conflict still
@Kyrtapz please help me resolve this conflict!

2021-11-11 01:13 UTC, flavio-fernandes commented on go-controller/pkg/kube/annotator.go
> +	// TODO(flaviof): need to resolve this conflict still
@Kyrtapz please help me resolve this conflict!

2021-11-11 01:13 UTC, flavio-fernandes commented on go-controller/pkg/kube/annotator.go
> +	// TODO(flaviof): need to resolve this conflict still
@Kyrtapz please help me resolve this conflict!

2021-11-11 20:30 UTC, flavio-fernandes commented on go-controller/pkg/kube/annotator.go
> +	// TODO(flaviof): need to resolve this conflict still
@trozet  After taking a closer look at `FailureHandlerFn` I can see that nothing in the codebase is using that.
So I'm leaning towards leaving this as is. In the 4.9 and newer codebases, this is completely removed.
Agree?

2021-11-11 20:30 UTC, flavio-fernandes commented on go-controller/pkg/kube/annotator.go
> +	// TODO(flaviof): need to resolve this conflict still
@trozet  After taking a closer look at `FailureHandlerFn` I can see that nothing in the codebase is using that.
So I'm leaning towards leaving this as is. In the 4.9 and newer codebases, this is completely removed.
Agree?

2021-11-11 20:30 UTC, flavio-fernandes commented on go-controller/pkg/kube/annotator.go
> +	// TODO(flaviof): need to resolve this conflict still
@trozet  After taking a closer look at `FailureHandlerFn` I can see that nothing in the codebase is using that.
So I'm leaning towards leaving this as is. In the 4.9 and newer codebases, this is completely removed.
Agree?

2021-11-11 20:47 UTC, flavio-fernandes commented
/retest

2021-11-12 01:21 UTC, flavio-fernandes commented
/retest-required

2021-11-13 03:19 UTC, trozet requested changes

2021-11-13 03:19 UTC, trozet commented on go-controller/hybrid-overlay/pkg/controller/node_windows.go
> +			if err := n.kube.SetAnnotationsOnNode(node.Name, map[string]interface{}{
you may want to just pull down:
https://github.com/openshift/ovn-kubernetes/commit/aecf6a4abaa8373b0e0efdb71e5b13f2074fe993#diff-0ce6ffe3c56c29376bb065cc84c336733740ac7e3d16c071c64f063826d2246b

to avoid having a conflict in this cherry pick as well as the following ones in annotator.go

2021-11-13 03:19 UTC, trozet commented on go-controller/pkg/kube/annotator.go
> +	annotations := make(map[string]interface{})
ditto if you pull down the previously mentioned commit, then you dont have the annotator conflicts on this one either

2021-11-13 03:19 UTC, trozet commented on go-controller/pkg/kube/annotator.go
> +	// TODO(flaviof): need to resolve this conflict still
remove it by rebasing on top of the commit I mentioned

2021-11-15 15:56 UTC, abhat commented
/retest

2021-11-15 17:07 UTC, flavio-fernandes commented on go-controller/hybrid-overlay/pkg/controller/node_windows.go
> +			if err := n.kube.SetAnnotationsOnNode(node.Name, map[string]interface{}{
ack. done.

2021-11-15 17:08 UTC, flavio-fernandes commented on go-controller/pkg/kube/annotator.go
> +	annotations := make(map[string]interface{})
ack. done.

2021-11-16 03:42 UTC, abhat commented
/retest

2021-11-16 20:00 UTC, flavio-fernandes commented
/retest-required

2021-11-17 00:38 UTC, flavio-fernandes commented
/retest-required

2021-11-17 01:22 UTC, trozet approved these changes
/lgtm

2021-11-17 01:25 UTC, trozet commented
/label backport-risk-assessed

2021-11-17 01:27 UTC, trozet commented
/retest

2021-11-17 03:38 UTC, abhat commented
/retest-required

2021-11-17 08:07 UTC, huiran0826 commented
/lgtm

2021-11-18 20:21 UTC, flavio-fernandes commented
/test e2e-metal-ipi-ovn-dualstack

2021-11-18 20:21 UTC, flavio-fernandes commented
/test 4.8-upgrade-from-stable-4.7-e2e-aws-ovn-upgrade

2021-11-19 02:56 UTC, flavio-fernandes commented
/test 4.8-upgrade-from-stable-4.7-e2e-aws-ovn-upgrade

2021-11-19 03:16 UTC, abhat commented
/bugzilla refresh

2021-11-19 03:24 UTC, abhat commented
/bugzilla refresh

2021-11-19 03:26 UTC, huiran0826 commented
/label cherry-pick-approved

2021-11-19 03:27 UTC, huiran0826 commented
/label qe-approved

2021-11-19 03:27 UTC, merged