Bug 2019809: 4.7 backport
openshift/ovn-kubernetes pull request #850
Opened 2021-11-29 17:56 UTC by astoycos

Backport the changes to fix 2019809 in 4.7 including all the commits from https://github.com/openshift/ovn-kubernetes/pull/686 

Specifically 

1. Add back checking for pod flows (to ensure the port that gets ovn_installed is the latest port for the pod)
2. Cancel oldest sandbox request if the pod's MAC or UUID changes. Basically if ovnkube is serving a CNI request and the mac was changed due to a pod delete/add event, cancel this request and move onto the newer pod.

Without the smartnic changes

2021-11-29 18:04 UTC, astoycos commented
/bugzilla refresh

2021-11-29 18:31 UTC, astoycos commented
/bugzilla refresh

2021-11-29 18:36 UTC, astoycos commented
/hold until CI looks good/ I can confirm I didn't miss anything here

2021-11-29 20:19 UTC, astoycos commented
/retest

2021-11-29 20:52 UTC, astoycos commented on go-controller/pkg/cni/cni.go
> +	// for Smart-Nic, ensure connection-details is present
Nit: Remove this comment... no Smart Nic in 4.7

2021-11-29 21:58 UTC, flavio-fernandes commented
It is a bit hard to see the conflicts as well as the commits that were cherry-picked because they are
not available in the commit message. Likely a NIT, but if not too late, can you re-run the cherry-pick commands with the `-x` flag?

2021-11-29 22:05 UTC, flavio-fernandes commented on go-controller/pkg/cni/cni.go
> +		result, err = request.cmdCheck(podLister, useOVSExternalIDs, kclient)
Question to self [Confused...]: where useOVSExternalIDs comes from? Maybe another commit...

2021-11-29 22:25 UTC, flavio-fernandes reviewed
that is not an easy backport! I have some suggestions, but please take them with a grain of salt as you have already accomplished more than I could. :P

2021-11-29 22:25 UTC, flavio-fernandes commented on go-controller/pkg/cni/utils.go
> +func isOvnReady(podAnnotation map[string]string) bool {
Which commit is isOvnReady frunction from?
I do not see it in https://github.com/openshift/ovn-kubernetes/pull/686/commits/c1b75f60e0dc7e8a5e041164588776b7e5dc8693

2021-11-29 22:25 UTC, flavio-fernandes commented on go-controller/pkg/cni/utils_test.go
> +package cni
Just curious: This while file is now, right? Had any troubles determining what tests to backport?

2021-11-29 22:25 UTC, flavio-fernandes commented on go-controller/pkg/cni/ovs.go
> +func isIfaceOvnInstalledSet(ifaceName string) bool {
New function from outside https://github.com/openshift/ovn-kubernetes/pull/686/commits/5954ef4a62787dccd9c583f011e827fe952397ad right? Is that from a specific commit, or latest on 4.8 release?

2021-11-29 22:25 UTC, flavio-fernandes commented on go-controller/pkg/cni/cni.go
> +<<<<<<< HEAD
oops! :)

2021-11-29 22:25 UTC, flavio-fernandes commented on go-controller/pkg/cni/cni.go
> +<<<<<<< HEAD
oops!

2021-11-29 22:25 UTC, flavio-fernandes commented on go-controller/pkg/cni/cniserver.go
> +	useOVSExternalIDs := false
This is form another commit, right? Should do we try to use that commit separately, or maybe just make mentioning of it in this commit?

2021-11-29 22:25 UTC, flavio-fernandes commented on go-controller/pkg/node/node_smartnic.go
> +package node
is this file needed for this backport?

2021-11-29 22:25 UTC, flavio-fernandes commented on go-controller/pkg/node/node_smartnic_test.go
> +package node
is this file needed for this backport?

2021-11-29 22:25 UTC, flavio-fernandes commented on go-controller/pkg/cni/cni.go
ah... maybe this fix should be done in the previous commit where the problem happen, so it does not mess up the flow of the backport?

2021-11-29 22:27 UTC, astoycos commented on go-controller/pkg/cni/cni.go
> +		result, err = request.cmdCheck(podLister, useOVSExternalIDs, kclient)
It's here https://github.com/openshift/ovn-kubernetes/pull/850/files#diff-7664be4fc9831cf07ad96809560316efd267b946033659d4e0973b8ceaa674cfR219 So It might have just gotten commited out of order

I'll try and see If I can clean this up

2021-11-30 14:03 UTC, astoycos commented on go-controller/pkg/cni/cni.go
I think this is fixed now

2021-11-30 14:09 UTC, astoycos commented on go-controller/pkg/cni/cniserver.go
> +	useOVSExternalIDs := false
I'm not too sure how to approach that... Like is is better to have "patch commits" beforehand or just fixup/add what we need in each commit?

The problem is, the commit history is pretty tight in this code so I don't think we can backport more commits to make everything clean

2021-11-30 14:11 UTC, astoycos commented on go-controller/pkg/cni/utils.go
> +func isOvnReady(podAnnotation map[string]string) bool {
It's actually from https://github.com/openshift/ovn-kubernetes/commit/ed3377b4208ebfa3ea728fcc2d5898b40be6224b

But that's a smart-nic commit... So we shouldn't really backport it

2021-11-30 14:12 UTC, astoycos commented on go-controller/pkg/cni/utils_test.go
> +package cni
To be honest I didn't pay too too much attention to the backports because the Unit tests are broken downstream in all our releases pre 4.10

2021-11-30 14:25 UTC, astoycos commented on go-controller/pkg/cni/cni.go
> +<<<<<<< HEAD
fixed :)

2021-11-30 14:25 UTC, astoycos commented on go-controller/pkg/cni/cni.go
> +<<<<<<< HEAD
fixed :)

2021-11-30 14:26 UTC, astoycos commented on go-controller/pkg/cni/ovs.go
> +func isIfaceOvnInstalledSet(ifaceName string) bool {
Yeah this function is from https://github.com/openshift/ovn-kubernetes/commit/09020087ce9f6080f8e056ab62933d9b4d324500 

Which is something we aren't backporting

2021-11-30 14:27 UTC, astoycos commented
Redid this, cherrypicking in order of original date committed rather than the cherry-pick order in https://github.com/openshift/ovn-kubernetes/pull/686 (made things a bit easier)

2021-11-30 14:48 UTC, astoycos commented
/test

2021-11-30 15:29 UTC, astoycos commented
Seeing some failures, bringing up a CLU with cluster bot to see what's going on

2021-11-30 16:19 UTC, astoycos commented
/retest-required

2021-11-30 16:54 UTC, astoycos commented
/retest-required

2021-11-30 17:57 UTC, astoycos commented
/retest

2021-11-30 19:20 UTC, astoycos commented
/assign @dcbw @trozet

2021-11-30 19:57 UTC, flavio-fernandes reviewed
@astoycos : I found a few discrepancies; they may be irrelevant, tho. PTAL.

2021-11-30 19:57 UTC, flavio-fernandes commented on go-controller/pkg/cni/cniserver.go
> +	useOVSExternalIDs := false
ack. no worries. I follow now

2021-11-30 19:57 UTC, flavio-fernandes commented on go-controller/pkg/cni/utils_test.go
> +package cni
Understood. There is some smartnic stuff in here that may give the impression it is part of 4.7; but you are right that w/out some pieces of it this backport would not be possible.

2021-11-30 19:57 UTC, flavio-fernandes commented on go-controller/pkg/cni/helper_linux.go
>  	// Find and remove any existing OVS port with this iface-id. Pods can
NIT: spacing seems off on this line

2021-11-30 19:57 UTC, flavio-fernandes commented on go-controller/pkg/cni/helper_linux.go
>  		klog.Warningf("Failed to settle addresses: %q", err)
hm... should we add a  return here?
I was hoping to see the `//END OCP HACK` marker here somewhere :)
Ref: https://github.com/openshift/ovn-kubernetes/pull/686/commits/3e876ef72a602facc916df749259a7b1e86360a9#diff-01a2ef868473804cd3d9b894b093e5be0735cfb21bf27f375ece3a33cc07edc9L360

2021-11-30 19:57 UTC, flavio-fernandes commented on go-controller/pkg/cni/types.go
> +type cniRequestFunc func(request *PodRequest, podLister corev1listers.PodLister, useOVSExternalIDs bool, kclient kubernetes.Interface, kubeAuth *KubeAPIAuth) ([]byte, error)
q: Are podLister and kclient (lines 106 and 107 above) still needed? They were removed in 
https://github.com/openshift/ovn-kubernetes/pull/686/commits/2171779d7fa6b015ff4e64710393391cdaeb0aa3

2021-11-30 19:58 UTC, astoycos commented on go-controller/pkg/cni/helper_linux.go
>  		klog.Warningf("Failed to settle addresses: %q", err)
It's there I believe :) 

https://github.com/openshift/ovn-kubernetes/pull/850/files#diff-01a2ef868473804cd3d9b894b093e5be0735cfb21bf27f375ece3a33cc07edc9R384

2021-11-30 20:35 UTC, flavio-fernandes commented on go-controller/pkg/cni/helper_linux.go
>  		klog.Warningf("Failed to settle addresses: %q", err)
in the 4.8 commit,  3e876ef72a602facc916df749259a7b1e86360a9  it seems that the code returns `return nil, err` instead of klog when `err = setupIPTablesBlocks(netns, ifInfo)` fails. That is my actual doubt.

2021-11-30 21:32 UTC, astoycos commented on go-controller/pkg/cni/types.go
> +type cniRequestFunc func(request *PodRequest, podLister corev1listers.PodLister, useOVSExternalIDs bool, kclient kubernetes.Interface, kubeAuth *KubeAPIAuth) ([]byte, error)
Hrm I still see them in 4.8... https://github.com/openshift/ovn-kubernetes/blob/release-4.8/go-controller/pkg/cni/cni.go#L232

2021-11-30 21:37 UTC, flavio-fernandes commented on go-controller/pkg/cni/types.go
> +type cniRequestFunc func(request *PodRequest, podLister corev1listers.PodLister, useOVSExternalIDs bool, kclient kubernetes.Interface, kubeAuth *KubeAPIAuth) ([]byte, error)
> 

ah, nvm. It must be unrelated to this backport and I got my wires crossed.

2021-12-01 09:04 UTC, anuragthehatter commented
job test upgrade 4.7.38 openshift/ovn-kubernetes#859,openshift/ovn-kubernetes#850 aws succeeded

2021-12-01 09:04 UTC, anuragthehatter commented
/lgtm
/label qe-approved

2021-12-01 19:46 UTC, trozet requested changes

2021-12-01 19:46 UTC, trozet commented on go-controller/pkg/cni/types.go
> +	podLister corev1listers.PodLister
why is this and kclient here? This doesn't look to be part of the 4.8 code.

2021-12-01 19:46 UTC, trozet commented on go-controller/pkg/cni/types.go
> +	podLister corev1listers.PodLister
It looks like in your version it is used in ConfigureInterface and the kclient and podLister arguments in func (pr *PodRequest) ConfigureInterface are unused.

2021-12-01 19:46 UTC, trozet commented on go-controller/pkg/cni/utils.go
> +func isOvnReady(podAnnotation map[string]string) bool {
we should backport it, because its also used in cmdAdd and cmdCheck:

```
func (pr *PodRequest) cmdAdd(kubeAuth *KubeAPIAuth, podLister corev1listers.PodLister, useOVSExternalIDs bool, kclient kubernetes.Interface) ([]byte, error) {
	namespace := pr.PodNamespace
	podName := pr.PodName
	if namespace == "" || podName == "" {
		return nil, fmt.Errorf("required CNI variable missing")
	}

	kubecli := &kube.Kube{KClient: kclient}
	annotCondFn := isOvnReady

	if pr.IsSmartNIC {
		// Add Smart-NIC connection-details annotation so ovnkube-node running on smart-NIC
		// performs the needed network plumbing.
		if err := pr.addSmartNICConnectionDetailsAnnot(kubecli); err != nil {
			return nil, err
		}
		annotCondFn = isSmartNICReady
	}
	// Get the IP address and MAC address of the pod
	// for Smart-Nic, ensure connection-details is present
	podUID, annotations, err := GetPodAnnotations(pr.ctx, podLister, kclient, namespace, podName, annotCondFn)
	if err != nil {
		return nil, fmt.Errorf("failed to get pod annotation: %v", err)
	}
	if err := pr.checkOrUpdatePodUID(podUID); err != nil {
		return nil, err
	}
```
It is used to get the podUID which is then used by  pr.checkOrUpdatePodUID(podUID) which was added by 
https://github.com/openshift/ovn-kubernetes/pull/850/commits/e34ab84ef4aeaf135f229f37202a5006cb976a06

2021-12-01 19:46 UTC, trozet commented on go-controller/pkg/node/node.go
> +func getOVNIfUpCheckMode() (bool, error) {
This is part of https://github.com/openshift/ovn-kubernetes/commit/09020087ce9f6080f8e056ab62933d9b4d324500 which isn't in 4.7 or being backported here right?

2021-12-01 19:46 UTC, trozet commented on go-controller/pkg/cni/cni.go
it's still a little out of order, but its fine. We can still just diff the entire contents of the PR.

2021-12-01 19:46 UTC, trozet commented on go-controller/pkg/cni/cniserver.go
> +	useOVSExternalIDs := false
its better to have picked the other required commits before applying these commits on top (unless you only need certain functions/pieces from a specific commit). In this case the commit is https://github.com/openshift/ovn-kubernetes/commit/09020087ce9f6080f8e056ab62933d9b4d324500

cni: Use new port-up OVN notification mechanism (when possible)

I dont think we should be backporting that into this PR. Why do you need it?

2021-12-01 19:46 UTC, trozet commented on go-controller/pkg/cni/helper_linux.go
>  		klog.Warningf("Failed to settle addresses: %q", err)
that's above at line 352/381:
https://github.com/openshift/ovn-kubernetes/pull/850/files#diff-01a2ef868473804cd3d9b894b093e5be0735cfb21bf27f375ece3a33cc07edc9L351

2021-12-01 19:56 UTC, astoycos commented on go-controller/pkg/node/node.go
> +func getOVNIfUpCheckMode() (bool, error) {
Yeah

2021-12-01 20:49 UTC, astoycos commented on go-controller/pkg/cni/types.go
> +	podLister corev1listers.PodLister
It is part of the 4.8 code though -> https://github.com/openshift/ovn-kubernetes/blob/release-4.8/go-controller/pkg/cni/types.go#L120 

But yeah if those vars aren't getting removed I can delete them

2021-12-01 21:56 UTC, astoycos commented on go-controller/pkg/cni/cniserver.go
> +	useOVSExternalIDs := false
I  didn't backport that commit..... Do you mean why did I need 

```
useOVSExternalIDs := false
if atomic.LoadInt32(&s.useOVSExternalIDs) > 0 {
		useOVSExternalIDs = true
	}
	result, err := s.requestFunc(req, s.podLister, useOVSExternalIDs, s.kclient, s.kubeAuth)
```

2021-12-01 22:02 UTC, astoycos commented on go-controller/pkg/cni/types.go
> +	podLister corev1listers.PodLister
Wait those are used in ConfigureInterface 
here -> [podLister](https://github.com/openshift/ovn-kubernetes/pull/850/files#diff-01a2ef868473804cd3d9b894b093e5be0735cfb21bf27f375ece3a33cc07edc9R373)

But in 4.8 we get them from as function inputs rather rather than the pod request, so I'll fix that

2021-12-02 04:26 UTC, astoycos commented
Based on an out of band conversation with @trozet, we have decided to remove https://github.com/openshift/ovn-kubernetes/commit/5954ef4a62787dccd9c583f011e827fe952397ad from this backport due to the fact that all we need to solve the the issues described in https://bugzilla.redhat.com/show_bug.cgi?id=2019809 is

- The Fixes added above to check for stale CNI requests 
- The fix for a race in the pod sync funtion -> https://github.com/openshift/ovn-kubernetes/pull/859

And we would like to avoid backporting ANYTHING extra unless we have to.

2021-12-02 04:46 UTC, astoycos commented
Based on an out of band conversation with @trozet, we have decided to remove https://github.com/openshift/ovn-kubernetes/commit/5954ef4a62787dccd9c583f011e827fe952397ad from this backport due to the fact that all we need to solve the the issues described in https://bugzilla.redhat.com/show_bug.cgi?id=2019809 is

- The Fixes added above to check for stale CNI requests 
- The fix for a race in the pod sync funtion -> https://github.com/openshift/ovn-kubernetes/pull/859

And we would like to avoid backporting ANYTHING extra unless we have to. 

@anuragthehatter If you could please Re-QE that'd be great 

@flavio-fernandes @trozet Please give this one final look, the backport was much simplier now so it shouldn't be too hard to review

2021-12-02 04:46 UTC, astoycos commented
/un hold

2021-12-02 04:47 UTC, astoycos commented
/un-hold

2021-12-02 04:48 UTC, astoycos commented
/unhold

2021-12-02 04:48 UTC, astoycos commented
/test-all

2021-12-02 04:49 UTC, astoycos commented
/test all

2021-12-02 04:49 UTC, astoycos commented
/retest-required

2021-12-02 11:13 UTC, flavio-fernandes commented
/test e2e-gcp-ovn

2021-12-02 15:04 UTC, trozet approved these changes
/lgtm

2021-12-02 15:04 UTC, trozet commented
/label backport-risk-assessed

2021-12-03 14:56 UTC, anuragthehatter commented
/label cherry-pick-approved

2021-12-03 14:58 UTC, merged